imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@CRMBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: zh_CN

framework:
    #esi:             ~
    #translator:
        #fallbacks: ["%locale%"]

    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~



# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    cache:            false
    strict_variables: "%kernel.debug%"
    form_theme:
                 - 'bootstrap_3_layout.html.twig'






# Doctrine Configuration
doctrine:
    dbal:
                driver:   pdo_sqlite
                host:     127.0.0.1
                port:     null
                dbname:   ji_crm
                user:     root
                password: null
                charset:  UTF8
                path:     "%kernel.root_dir%/data/ji_crm.sqlite"



        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true



        auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name:           main
    user_class:              UserBundle\Entity\User
    use_listener:            true
    use_flash_notifications: true
    use_username_form_type:  true

    group:
       group_class: AppBundle\Entity\Group
       group_manager:  fos_user.group_manager.default
       form:
           type:               fos_user_group
           name:               fos_user_group_form
           validation_groups:  [Registration, Default]
    service:
       mailer:                 fos_user.mailer.default
       email_canonicalizer:    fos_user.util.canonicalizer.default
       username_canonicalizer: fos_user.util.canonicalizer.default
       token_generator:        fos_user.util.token_generator.default
       user_manager:           fos_user.user_manager.default

    profile:
       form:
           type: app_user_profile

    resetting:
      email:
        from_email:
           address:     hkgbfmail@163.com
           sender_name: Resetting Password


knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

lexik_jwt_authentication:
    private_key_path: '%kernel.root_dir%/var/jwt/private.pem'
    public_key_path:  '%kernel.root_dir%/var/jwt/public.pem'
    pass_phrase:      'kcswag'
    token_ttl:        86400


nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
        paths:
            '^/api/':
                allow_credentials: true
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'GET']
                max_age: 3600


