# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.jwt_token_authenticator:
            class: AppBundle\Security\JwtAuthenticator
            arguments: ['@doctrine.orm.entity_manager', '@lexik_jwt_authentication.jwt_encoder']

    client_manager_controller:
            class: CRMBundle\Controller\ClientManagerController

    client_asset_controller:
            class: CRMBundle\Controller\ClientAssetController

    distribution_controller:
            class: CRMBundle\Controller\DistributionController

    help_controller:
            class: CRMBundle\Controller\HelpController

    crmbundle_default_controller:
            class: CRMBundle\Controller\DefaultController

    statistic_data_controller:
            class: CRMBundle\Controller\StatisticDataController

    export_controller:
            class: AppBundle\Controller\ExportController

